# SPDX-License-Identifier: Apache-2.0
FROM ubuntu:20.04@sha256:8feb4d8ca5354def3d8fce243717141ce31e2c428701f6682bd2fafe15388214

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       build-essential=12.8ubuntu1.1 \
       cmake=3.16.3-1ubuntu1.20.04.1 \
       g++=4:9.3.0-1ubuntu2 \
       g++-9=9.4.0-1ubuntu1~20.04.2 \
       gcc=4:9.3.0-1ubuntu2 \
       gcc-9=9.4.0-1ubuntu1~20.04.2 \
       git=1:2.25.1-1ubuntu3.14 \
       libc6-dev=2.31-0ubuntu9.18 \
       make=4.2.1-1.2 \
       python3=3.8.2-0ubuntu2 \
       python3.8=3.8.10-0ubuntu1~20.04.18 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
